server:
  port: 8888
spring:
  application:
    name: GOFISHING-ZUUL
zuul:
  ignoredServices: '*'
  routes:
    plat:
      serviceId: GOFISHING-PLAT
      path: /plat/**
    product:
      serviceId: GOFISHING-PRODUCT
      path: /product/**
    common:
      serviceId: GOFISHING-COMMON
      path: /common/**
  prefix: /services
#zuul超时时间的设置
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 6000
ribbon:
  ConnectTimeout: 6000
  ReadTimeout: 6000
 