server:
  port: 8888
spring:
  application:
    name: GOFISHING-ZUUL
zuul:
  ignoredServices: '*'
  routes:
    plat:
      serviceId: GOFISHING-PLAT
      path: /plat/**
    product:
      serviceId: GOFISHING-PRODUCT
      path: /product/**
  prefix: /services
