server:
  port: 8888
spring:
  application:
    name: GOFISHING-ZUUL
zuul:
  ignoredServices: '*' #只能通过路由访问，不能使用服务名访问
  routes:
    plat:
      serviceId: GOFISHING-PLAT
      path: /plat/**
  prefix: /services
