server:
  port: 8083
spring:
  application:
    name: GOFISHING-PLAT

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://root:root@localhost:8761/eureka/
